find_path(PMEMOBJ_INCLUDE_DIR libpmemobj.h HINTS ${PMEMOBJ_PATH}/include)
find_library(PMEMOBJ_LIBRARY libpmemobj HINTS ${PMEMOBJ_PATH}/lib)
find_library(PMEM_LIBRARY libpmem HINTS ${PMEMOBJ_PATH}/lib)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PMEMOBJ REQUIRED_VARS PMEMOBJ_LIBRARY PMEM_LIBRARY PMEMOBJ_INCLUDE_DIR FAIL_MESSAGE DEFAULT_MSG)

if(PMEMOBJ_FOUND)
	set(PMEMOBJ_LIBRARIES ${PMEMOBJ_LIBRARY} ${PMEM_LIBRARY})
	set(PMEMOBJ_INCLUDE_DIRS ${PMEMOBJ_INCLUDE_DIR})
else()
	message(obj not found)
endif()

mark_as_advanced(PMEMOBJ_LIBRARY PMEM_LIBRARY PMEMOBJ_INCLUDE_DIR)
